# Generated by Django 6.0.4 on 2026-07-13 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="Количество"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Цена, ₽"
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукция",
                "verbose_name_plural": "Продукция",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fio", models.CharField(max_length=255, verbose_name="ФИО подавшего")),
                (
                    "org_name",
                    models.CharField(max_length=255, verbose_name="Организация"),
                ),
                ("inn", models.CharField(max_length=20, verbose_name="ИНН/КПП")),
                (
                    "legal_address",
                    models.CharField(max_length=500, verbose_name="Юридический адрес"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Электронная почта"),
                ),
                (
                    "items",
                    models.JSONField(default=list, verbose_name="Позиции заказа"),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="Сумма"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("новое", "Новое"),
                            ("подтверждено", "Подтверждено"),
                            ("отклонено", "Отклонено"),
                        ],
                        default="новое",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["-created_at"],
            },
        ),
    ]
